### ISSUE TITLE
[Accessibility] No focus when visiting hfs

### ISSUE THREAD

**Issue by Timtam** [rejetto/hfs#593] opened 2024-05-14 18:40 UTC
Right now, when using HFS 0.52.7 with a screen reader like the freely available NVDA, visiting the page will cause the web interface to not get auto-focused. Instead you'll have to press tab or re-focus the window once by tabbing out and back in. That is kinda abnormal behaviour as that isn't what happens with any other webpage.

**To Reproduce**
1. Launch NVDA
2. Go to 'https://hoard.reaperaccessibility.com
3. Notice how you don't get any speech feedback although the webpage has loaded.

**Describe the bug**

I don't know what exactly causes this issue, but its a little bit annoying as we'll have to deal with alot of people who might not know how to properly handle this behaviour. As described above, the auto-focus doesn't seem to work well. Maybe focus should be moved manually after finishing the web page load to the very first element of the UI, e.g. the navigation or something?

**Environment (please complete the following information):**
 - OS: Linux
 - HFS Version 0.52.7
 - Browser Chrome (it seems to work on Firefox)
 - Screen Reader NVDA (latest alpha)

**Comment by rejetto** [comment] 2024-05-14 21:50
I use a mac and make my tests with VoiceOver, I cannot install nvda.
But i noticed that at start the focus is on a hidden element, that may be the cause.
I made a fix. Can you give me a feedback to my solution?
0.53.0-alpha2.2 [hfs-linux.zip](https://github.com/rejetto/hfs/files/15314083/hfs-linux.zip)

not sure if you are using binary or npx

**Comment by Timtam** [comment] 2024-05-15 06:59
I'm running via npx since i'm running on ARM Linux. Could you publish it via npx so that I can give it a try? Thanks!

**Comment by rejetto** [comment] 2024-05-15 07:54
sure, you can get it with npx hfs@exp

**Comment by Timtam** [comment] 2024-05-15 07:58
Thanks. Yep, that seems to have fixed the error. Thanks alot!

**Comment by rejetto** [comment] 2024-05-15 07:58
thanks for your feedback!

**Comment by rejetto** [comment] 2024-05-15 10:39
fixed in 0.53.0-alpha3
thanks

**Closed as completed by rejetto** 2024-05-15 10:39 UTC
Labels: bug
