### ISSUE TITLE
"Download zip" option downloads only a single file inside the zip

### ISSUE THREAD

**Issue by hllmtl** [rejetto/hfs#70] opened 2022-08-07 06:47 UTC
**Describe the bug**
I've also tried selecting all in filter list before clicking "download zip" to no avail.
It downloads everything correctly if I only have virtual folders. But if I add a folder from disk anywhere (root/home level or inside a virtual folder) then it again downloads a single file only.

**Environment:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 0.25.0

**Comment by rejetto** [comment] 2022-08-07 22:11
i tried to reproduce your problem in many ways, but i always got a good zip with everything in it.
1. record a video, or even a sequence of a few screenshots.
2. What are you using to open the zip?
3. You may be seeing just 1 file for some reason while the zip still has the rest. Try something like this: a folder with mp3 or jpeg files (at least 2 files). Make the "wrong" single-file zip, and see if the size of the zip file is close to the size of the single file you see in it.
4. try attaching an example zip file that's supposed to contain more than 1 file.

**Comment by hllmtl** [comment] 2022-08-08 03:49
@rejetto I use 7-Zip. I just downloaded and tried with PeaZip and WinRAR as well. 7-Zip and PeaZip don't say anything when I open the zip but say "Unexpected end of data" when I try to open the only file there is. WinRAR immediately says "Unexpected end of archive" when I open the zip, and says "The archive is corrupt" when I try to open the file.
So basically the archive is corrupt (its size is as if it has all the files though).

But I think I just figured out why it happens after trying bunch of random stuff. Everything started working correctly when I stopped sharing the `logs` folder (HFS' logs folder). When I add it back HFS starts to create corrupt archives again. Now you might ask "why the hell would you share that folder...", the answer is I shared everything inside the `hfs` folder when I initially started testing HFS because it's the folder that opens by default when the `Add` button is clicked lol. Then I added/shared other stuff on top of those...

Can you try to reproduce that? If you can't again, then I'll try to screen record multiple scenarios when I can. But I'm pretty sure that's the culprit. I've attached one of the corrupt archives just in case. It's supposed to have `logs/access.log`, `logs/access-error.log` and a 13.4 MB binary (`yt-dlp.exe`).

[archive.zip](https://github.com/rejetto/hfs/files/9278533/archive.zip)

**Comment by rejetto** [comment] 2022-08-08 14:52
ok, that was the missing information to reproduce the problem.
Further investigation led me to determine that the problem was caused by the file's (log) increase in size during the process (size is read first, and content just later).
While the problem with a shrinking file will persist, a growing file like this is more common, and I can workaround the problem by interrupting reading once the initial size is reached.
Fix will be included in next release.

**Closed as completed by rejetto** 2022-08-08 14:52 UTC
Labels: bug
