### ISSUE TITLE
Drag and Drop "Upload terminated"

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#159] opened 2023-03-15 16:14 UTC
When dragging a file into the folder to upload it, it will successfully upload yet will show `Upload terminated` error.

**Environment:**
 - OS: Windows 11 22H2 22621.1344
 - Browser: Chrome 112
 - Version: 0.40.1

**Comment by rejetto** [comment] 2023-03-18 16:40
i tried both on windows11 and on my mac, and couldn't reproduce the problem.
You may consider attaching a video of the problem, in case I can spot some useful detail in it.

**Comment by rejetto** [comment] 2023-03-18 17:37
it's not an error, just bad english.
fixed in next release.

**Closed as completed by rejetto** 2023-03-18 17:37 UTC
Labels: bug
